services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./recordings:/app/recordings
      - ./transcripts:/app/transcripts
      - ./notes:/app/notes
    env_file:
      - .env
    restart: unless-stopped
